import { Loader2, Mail } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { AuthButton } from '../components/auth/AuthButton'
import { AuthLayout } from '../components/auth/AuthLayout'
import { FormInput } from '../components/auth/FormInput'
import { PasswordInput } from '../components/auth/PasswordInput'
import { useAuth } from '../contexts/AuthContext'
import { isValidEmail } from '../utils/validation'
type LoginErrors = Partial<Record<'email' | 'password' | 'form', string>>
export function LoginPage() { const { t } = useTranslation('auth'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [errors, setErrors] = useState<LoginErrors>({}); const [isSubmitting, setIsSubmitting] = useState(false); const navigate = useNavigate(); const location = useLocation(); const { login, user, isAuthenticated } = useAuth(); useEffect(() => { if (isAuthenticated && user) navigate(user.role === 'admin' ? '/admin/dashboard' : '/teacher/dashboard', { replace: true }) }, [isAuthenticated, navigate, user]); async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const next: LoginErrors = {}; if (!isValidEmail(email)) next.email = t('validation.invalidEmail'); if (!password) next.password = t('validation.passwordRequired'); setErrors(next); if (Object.keys(next).length) return; setIsSubmitting(true); try { const currentUser = await login(email, password); const requestedPath = (location.state as { from?: string } | null)?.from; const allowedRequest = requestedPath && ((currentUser.role === 'teacher' && requestedPath.startsWith('/teacher/')) || (currentUser.role === 'admin' && requestedPath.startsWith('/admin/'))); navigate(allowedRequest ? requestedPath : currentUser.role === 'admin' ? '/admin/dashboard' : '/teacher/dashboard') } catch (error) { setErrors({ form: error instanceof Error ? error.message : t('validation.network') }) } finally { setIsSubmitting(false) } } return <AuthLayout title={t('login.title')} description={t('login.description')}><form onSubmit={handleSubmit} noValidate className="mt-7 space-y-5">{errors.form && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{errors.form}</p>}<FormInput id="login-email" label={t('fields.email')} type="email" dir="ltr" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" placeholder={t('fields.emailPlaceholder')} error={errors.email} icon={<Mail className="size-4" />} disabled={isSubmitting} /><PasswordInput id="login-password" label={t('fields.password')} value={password} onChange={setPassword} autoComplete="current-password" error={errors.password} disabled={isSubmitting} /><AuthButton type="submit" disabled={isSubmitting}>{isSubmitting ? <><Loader2 className="size-5 animate-spin" aria-hidden="true" />{t('login.submitting')}</> : t('login.submit')}</AuthButton></form><p className="mt-6 text-center text-sm text-slate-500">{t('login.noAccount')} <Link to="/register" className="font-bold text-emerald-700 hover:underline">{t('login.registerLink')}</Link></p></AuthLayout> }
